---
- name: Debug execution data
  ansible.builtin.debug:
    msg: "Running validate action"

- name: Load action variables
  ansible.builtin.set_fact:
    action: "{{ item.name }}"
    data: "{{ item.vars | d({}) }}"
    provider: "{{ item.vars.provider | d(provider) }}"

- name: "Validate configuration data against defined schema for provider - {{ provider }}"
  ansible.utils.validate:
    data: "{{ data }}"
    criteria: "{{ lookup('file', 'files/schemas/providers/{{ provider }}/{{ action }}.json') | from_json }}"
    engine: ansible.utils.jsonschema
  vars:
    ansible_jsonschema_draft: draft7
  register: result

- name: "Start action for provider {{ provider }}"
  ansible.builtin.include_tasks: "providers/{{ provider }}/{{ action }}.yaml"

- name: Debug execution data
  ansible.builtin.debug:
    msg: "Completed validate action"
